2024-11-24 15:16:45,225 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\URBAN\pythonProject1\tests_12_4.py", line 23, in test_run
    runner = Runner(2)     # Создаем объект Runner с произвольным именем
  File "C:\URBAN\pythonProject1\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-24 15:16:45,233 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\URBAN\pythonProject1\tests_12_4.py", line 12, in test_walk
    runner = Runner('noName', -5)     # Создаем объект Runner с произвольным именем
  File "C:\URBAN\pythonProject1\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
